site_name: Flemish Archive for Annotated Music
site_author: Nicholas Cornia
repo_url: https://github.com/nicholascornia89/faam
nav:
  - Project: index.md
  - Acknowledgements: acknowledgements.md
  - Special Collections: special_collections.md
  - Publications: publications.md
  - Music Annotation Ontology: music_annotation_ontology.md

plugins:
  - search
  - mkdocs-video

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/glide.core.css
  - assets/stylesheets/glide.theme..css

#extra_javascript:
  #- assets/javascripts/

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/faam-logo-gold.png
  favicon: assets/images/favicon.ico
  language: en
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      abstract: fontawesome/solid/book
      note: fontawesome/solid/note-sticky
      quote: fontawesome/solid/quote-left

  font:
    text: Poppins
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      default: custom
      footer: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      default: custom
      footer: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


      
  features:
    #- navigation.instant
    #- navigation.instant.prefetch
    #- navigation.instant.progress
    - search.share
    #- navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.top
    - toc.follow
    - toc

copyright: Copyright &copy; 2025 Royal Conservatoire of Antwerp, Artesis Plantijn University College

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nicholascornia89/faam
      name: GitHub repository

markdown_extensions:
  - footnotes
  - tables
  - attr_list
  - admonition
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

